#!/bin/bash

GIT_GAGA_FILE="./.gitgaga"
GIT_GAGA_FILE_LIST=$(cat $GIT_GAGA_FILE | grep -v "#")

decrypt_git_gaga_files(){
    for file in "${GIT_GAGA_FILE_LIST[@]}"; do
        openssl enc -d -aes-256-cbc -salt -pbkdf2 -in "$file.enc" -out $file
        echo "> encrypted '$file.enc' to '$file'"
    done
}

decrypt_git_gaga_files
